version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./brokers.db:/app/brokers.db
    environment:
      - SECRET_KEY=change-this-secret-key-in-production
      - FLASK_ENV=production
    restart: unless-stopped

  # Optional: Add nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app
  #   restart: unless-stopped
